name: funny_tic_tac_toe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  assets_audio_player: ^3.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/icons/


